/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#8c4f16',
        'primary-container': '#e89b5c',
        'on-primary-container': '#653300',
        'primary': '#8c4f16',
        'on-primary': '#ffffff',
        'primary-fixed': '#ffdcc3',
        'primary-fixed-dim': '#ffb77f',
        'on-primary-fixed': '#2f1500',
        'on-primary-fixed-variant': '#6f3900',
        'inverse-primary': '#ffb77f',
        'secondary': '#705b3e',
        'on-secondary': '#ffffff',
        'secondary-container': '#f9dbb7',
        'on-secondary-container': '#755f42',
        'secondary-fixed': '#fcdeba',
        'secondary-fixed-dim': '#dfc29f',
        'on-secondary-fixed': '#281903',
        'on-secondary-fixed-variant': '#574329',
        'tertiary': '#496549',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#95b594',
        'on-tertiary-container': '#2b472d',
        'tertiary-fixed': '#caebc8',
        'tertiary-fixed-dim': '#afcfad',
        'on-tertiary-fixed': '#05210b',
        'on-tertiary-fixed-variant': '#314d33',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#fff8f5',
        'surface-dim': '#e5d7d0',
        'surface-bright': '#fff8f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff1e9',
        'surface-container': '#f9ebe4',
        'surface-container-high': '#f3e5de',
        'surface-container-highest': '#eee0d8',
        'on-surface': '#211a16',
        'on-surface-variant': '#534439',
        'outline': '#857468',
        'outline-variant': '#d8c2b5',
        'inverse-surface': '#372f2a',
        'inverse-on-surface': '#fceee6',
        'surface-variant': '#eee0d8',
        'background': '#fff8f5',
        'on-background': '#211a16',
        // Custom tokens
        'background-warm': '#FBF7F0',
        'surface-pure': '#FFFFFF',
        'text-secondary': '#8B7E74',
        'accent-yellow': '#F4C95D',
        'border-subtle': '#EFE6D8',
        'progress-green': '#A8C8A6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'reading-width': '680px',
        'container-max': '1024px',
        gutter: '1.5rem',
        'card-padding': '1.5rem',
        'section-gap': '4rem',
      },
      fontFamily: {
        'body-main': ['Noto Serif SC', 'serif'],
        'h1': ['Noto Serif SC', 'serif'],
        'h2': ['Noto Serif SC', 'serif'],
        'display-title': ['Noto Serif SC', 'serif'],
        'body-italic': ['Noto Serif SC', 'serif'],
        'helper-text': ['Noto Serif SC', 'serif'],
        'label-capsule': ['Noto Serif SC', 'serif'],
      },
      fontSize: {
        'display-title': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'h1': ['28px', { lineHeight: '1.3', fontWeight: '700' }],
        'h2': ['22px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-main': ['16px', { lineHeight: '1.8', fontWeight: '400' }],
        'body-italic': ['16px', { lineHeight: '1.8', fontWeight: '400' }],
        'helper-text': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-capsule': ['12px', { lineHeight: '1', fontWeight: '600' }],
      },
      maxWidth: {
        'reading-width': '680px',
        'container-max': '1024px',
      },
    },
  },
  plugins: [],
}
